export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
