export const FETCH_TVSHOW = "FETCH_TVSHOW";
export const FETCH_TVSHOW_START = "FETCH_TVSHOW_START";
export const FETCH_TVSHOW_ERROR = "FETCH_TVSHOW_ERROR";
export const FETCH_TVSHOW_SUCCESS = "FETCH_TVSHOW_SUCCESS";
